### ISSUE TITLE
关闭SlideView时,按住后手指移动,SlideView没有跟随手指滑动关闭,需抬起后才能关闭

### ISSUE THREAD

**Issue by cizkey** [yanbober/SlideLayout#3]
关闭SlideView时,按住后手指移动,SlideView没有跟随手指滑动关闭,需抬起后才能关闭

具体描述;
当SlideView打开, 手指按住滑动关闭时. SlideView一开始会慢慢收回一部分. 
手指继续移动, SlideView将不会再移动. 显示一小部分布局.
直至手机抬起之后, 才会平滑关闭. 

测试手机: 
nubia z7 mini  (NX507J)
6.0.1 API 23

**Comment by cizkey** [comment]
我在dispathTouchEvent 打来3处log,  发现一个很奇怪的问题......
`    
@Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        int eventX = (int) event.getX();
        int eventY = (int) event.getY();
        int scrollX = getScrollX();
        int scrollY = getScrollY();
        Log.e(TAG, "scrollX: " + scrollX);   // 第一处  scrollX
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                mLastX = (int) event.getX();
                mLastY = (int) event.getY();
                mIsScrolling = false;
                //Maybe child not set OnClickListener, so ACTION_DOWN need to return true and use super.
                super.dispatchTouchEvent(event);
                return true;
            case MotionEvent.ACTION_MOVE:
                int offsetX = eventX - mLastX;
                int offsetY = eventY - mLastY;
                Log.e(TAG, "offsetX: " + offsetX);  //第二处   offsetX
                int directionMoveOffset = 0;
                if (mSlideDirection == SLIDE_LEFT || mSlideDirection == SLIDE_RIGHT) {
                    directionMoveOffset = Math.abs(offsetX) - Math.abs(offsetY);
                } else {
                    directionMoveOffset = Math.abs(offsetY) - Math.abs(offsetX);
                }
                if (directionMoveOffset < ViewConfiguration.getTouchSlop()) {
                    break;
                }
                getParent().requestDisallowInterceptTouchEvent(true);
                mIsScrolling = true;
                int newScrollX = 0;
                int newScrollY = 0;
                switch (mSlideDirection) {
                    case SLIDE_RIGHT:
                        newScrollX = scrollX - offsetX;
                        Log.e(TAG, "newScrollX: " + newScrollX);  //第三处   newScrollX
                        if (newScrollX < 0) {
                            newScrollX = 0;
                        } else if (newScrollX > mSlideView.getMeasuredWidth()) {
                            newScrollX = mSlideView.getMeasuredWidth();
                        }
                        break;
`

log日志为:
`
scrollX: 150
offsetX: 4
scrollX: 150
offsetX: 9
newScrollX: 141    //开始滑动时会输出newScrollX
scrollX: 141
offsetX: 6
scrollX: 141
offsetX: 2
scrollX: 141  
offsetX: 1  //继续移动, 会走ACTION_MOVE. 但是没有再输出newScrollX
scrollX: 141
//...........................省略
`

这个log说明
`
  case SLIDE_RIGHT:
                        newScrollX = scrollX - offsetX;
                        Log.e(TAG, "newScrollX: " + newScrollX);  //第三处   newScrollX
`
具体什么原因还在调试.

从测试的效果来看.  手指快速滑动关闭没有问题. 这个问题只有手指慢慢滑动时才存在.

**Comment by yanbober** [comment]
@cizkey 感谢反馈。
