### ISSUE TITLE
请教..

### ISSUE THREAD

**Issue by littleKun** [yanbober/SlideLayout#4]
确实很好用 想请教一下 在listview中如何实现 当已经打开了一个侧滑状态,再滑动另一个侧滑状态时,前一个如何自动关闭 就像qq一样

**Comment by yanbober** [comment]
@littleKun 
两个方案：
1、在你 Adapter 中类似 item 中选中标记那样处理，当有展开的调用关闭，不是很推荐。
2、基于现在自定义进行二次拓展，让其支持，不难的，欢迎提交 pr。
